# In this section you can enable/disable each module of the plugin.
modules:
  broadcast: true
  chat-censorship: true
  commandspy: true
  command-blocker: true
  command-warning: true
  globalchat: true
  help: true
  hub: true
  ip-limiter: true
  moderation: true
  messages: true
  nickname-blocker: true
  same-ip-broadcast: true
  socialspy: true
  staffchat: true

# Storage settings
# Storage options:
# => Remote databases
# ==> MySQL
# ==> MariaDB (preferred over MySQL)
# ==> PostgreSQL
# => Flatfile/local databases
# ==> H2
# ==> SQLite
storage-type: H2

# MySQL/MariaDB/PostgreSQL settings
# Modify the values below only if you are using a remote database.
data:
  # Define the address and port for the database.
  # If not defined, the default port will be used.
  # (MySQL/MariaDB: 3306, PostgreSQL: 5432)
  # Format: host:port
  address: localhost

  # The name of the database to use.
  database: minecraft

  # Credentials
  username: minecraft
  password: password

  # The prefix of all VelocityCompact tables.
  table-prefix: 'vc_'

  # The settings below apply to the MySQL/MariaDB connection pool.
  # The default values will be suitable for most servers.
  # Do not change these values unless you know what you are doing.
  pool:
    # Enable or disable the connection pool.
    enabled: true
    # The maximum number of connections that can be created in the pool.
    maximum-pool-size: 10
    # The minimum number of idle connections that the pool will try to maintain.
    minimum-idle: 10
    # The maximum lifetime of a connection in the pool.
    maximum-lifetime: 1800000 # 30 minutes
    # The maximum time that a connection is allowed to sit idle in the pool.
    keepalive-time: 0
    # The maximum time that the pool will wait for a connection to be returned before throwing an exception.
    connection-timeout: 5000 # 5 seconds

# Chat censorship settings
# This includes both chat messages and private messages
chat-censorship:
  # The words in this list will be censored.
  # This list is case-insensitive.
  censored-words: [ ]
  # The regular expressions in this list will be censored.
  censored-regex: [ ]
  punishment:
    # Should the player be punished for using a censored word?
    # Moderation should be enabled for this to work.
    enabled: true
    # The punishment type.
    # Available options: "warn", "mute", "gmute", "kick", "gkick", "ban", "gban"
    type: "warn"
    # The punishment duration in seconds.
    # Only available for "mute" and "ban" punishments.
    duration: 3600 # 1 hour
    # Should the punishment be silent?
    # If the punishment is silent only the player and staff members will be notified.
    silent: true

# Commandspy settings
commandspy:
  # Depending on the value of 'list-is-whitelist', the 'server-list' will be either a whitelist or a blacklist.
  # If 'list-is-whitelist' is set to 'true', only the servers in the list will be considered for commandspy.
  # If 'list-is-whitelist' is set to 'false', the servers in the list will be ignored for commandspy.
  server-list: [ ]
  list-is-whitelist: false
  # Player in this list will be ignored by commandspy.
  player-bypass: [ ]
  # Commands in this list will be ignored by commandspy.
  # Socialspy monitored commands are already ignored if socialspy is enabled.
  ignored-commands: [ ]

# The commands in this list will be blocked and not forwarded to the server.
blocked-commands:
  - "op"
  - "plugin"
  - "plugins"
  - "pl"
  - "bukkit:plugin"
  - "bukkit:plugins"
  - "bukkit:pl"
  - "minecraft:me"
  - "bukkit:?"
  - "icanhasbukkit"

# The commands in this list will trigger a warning message when executed.
# Commands in the 'blocked-commands' list will already trigger a warning message.
command-warning: [ ]

# Globalchat settings
globalchat:
  # Depending on the value of 'list-is-whitelist', the 'server-list' will be either a whitelist or a blacklist.
  # If 'list-is-whitelist' is set to 'true', only the servers in the list will be considered for globalchat.
  # If 'list-is-whitelist' is set to 'false', the servers in the list will be ignored for globalchat.
  server-list: [ ]
  list-is-whitelist: false

ip-limiter:
  # The maximum number of connections that can be made from the same IP address.
  max-connections: 5
  whitelist:
    # The IP addresses in this list will be ignored by the IP limiter.
    # You can use subnets to whitelist multiple IP addresses.
    # Example: 192.168.0.0/24 will whitelist all IP addresses from 192.168.0.1 to 192.168.0.254.
    ip-addresses: [ ]
    # The players in this list will be ignored by the IP limiter.
    nicknames: [ ]

# Moderation settings
moderation:
  # Should staff members provide a reason when punishing a player?
  punishment-needs-reason: true
  # Should staff members provide a reason when revoking a punishment?
  revoke-needs-reason: false
  # If this is set to true and a player is muted, they can't send private messages to other players.
  mute-prevents-private-messages: true
  # If this is set to true a server punishment (the one without the g) will be broadcast only in that server.
  broadcast-server-punishment-only-in-server: false
  # Player in these lists cannot be punished.
  bypass:
    ban: [ ]
    kick: [ ]
    mute: [ ]
    warn: [ ]
  # TODO Automatic punishment after x warning

# Players whose nickname is in this list will not be able to join the server.
# You can use regular expressions to block multiple nicknames.
blocked-nicknames: [ ]

# Players in this list will be ignored by same ip broadcast.
same-ip-broadcast-ignored-players: [ ]

# Socialspy settings
socialspy:
  # Depending on the value of 'list-is-whitelist', the 'server-list' will be either a whitelist or a blacklist.
  # If 'list-is-whitelist' is set to 'true', only the servers in the list will be considered for socialspy.
  # If 'list-is-whitelist' is set to 'false', the servers in the list will be ignored for socialspy.
  server-list: [ ]
  list-is-whitelist: false
  # Player in this list will be ignored by socialspy.
  player-bypass: [ ]

# Command aliases
command-aliases:
  ban: [ ]
  banip: [ ]
  broadcast: [ "bcast" ]
  commandspy: [ "cspy" ]
  gban: [ ]
  gbanip: [ ]
  gbroadcast: [ "gbcast" ]
  gkick: [ ]
  gkickip: [ ]
  globalchat: [ "gchat", "gc" ]
  gmute: [ ]
  gmuteip: [ ]
  gtempban: [ ]
  gtempbanip: [ ]
  gunban: [ ]
  gunbanip: [ ]
  gunmute: [ ]
  gunmuteip: [ ]
  kick: [ ]
  kickip: [ ]
  lookup: [ "playerinfo", "playeri" ]
  lookupip: [ "ipinfo" ]
  help: [ "h", "?" ]
  hub: [ "lobby" ]
  message: [ "msg", "m", "whisper", "w", "tell" ]
  mute: [ ]
  muteip: [ ]
  reply: [ "r" ]
  socialspy: [ "sspy" ]
  staffchat: [ "schat" ]
  tempban: [ ]
  tempbanip: [ ]
  tempmute: [ ]
  tempmuteip: [ ]
  unban: [ ]
  unbanip: [ ]
  unmute: [ ]
  unmuteip: [ ]
  velocitycompactreload: [ "vcreload" ]
  warn: [ ]

# Do not change this value. It is used to check if the config file is up to date.
file-version: 1